version: '3.1'

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    restart: always
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=$USER
      - COUCHDB_PASSWORD=$PASS
    volumes:
      - /LiveSync-CouchDB/couchdb/data/:/opt/couchdb/data
      - /LiveSync-CouchDB/couchdb/conf/local.ini:/opt/couchdb/etc/local.ini

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /LiveSync-CouchDB/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /LiveSync-CouchDB/nginx/certbot/conf:/etc/letsencrypt
      - /LiveSync-CouchDB/nginx/www:/var/www/
    depends_on:
      - couchdb

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - /LiveSync-CouchDB/nginx/certbot/conf:/etc/letsencrypt
      - /LiveSync-CouchDB/nginx/www:/var/www/
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait 26193{!}; certbot renew; done'
